

# This works if the scritp is execute in the right folder.
# If not, you need to change '.' with another folder, could be app/, ../app/, and so on.
sample-deploy-invocation:
	gcloud run deploy my-php-app --source . --region europe-west8 --allow-unauthenticated
